# The values are comupted manually from https://app.gazebosim.org/RudisLaboratories/fuel/models/OakD-Lite

header:
  seq: 0
  stamp:
    sec: 0
    nanosec: 0
  frame_id: "camera_link"

width: 1920
height: 1080
distortion_model: "plumb_bob"
D: [0, 0, 0, 0, 0]

K: [1393.32, 0.0, 960.0,
    0.0, 1393.32, 540.0,
    0.0, 0.0, 1.0]

R: [1, 0, 0,
    0, 1, 0,
    0, 0, 1]

P: [1393.32, 0, 960, 0,
    0, 1393.32, 540, 0,
    0, 0, 1, 0]


# depth image instrict in formation
# height: 480
# width: 848
# # width: 640

# distortion_model: "plumb_bob"
# D: [0.0, 0.0, 0.0, 0.0, 0.0]

# K: [440.07, 0.0, 424.0, 0.0, 440.07, 240.0, 0.0, 0.0, 1.0]

# R: [1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0]

# P: [440.07, 0.0, 424.0, 0.0, 0.0, 440.07, 240.0, 0.0, 0.0, 0.0, 1.0, 0.0]

